name: Auto Update Cookie

on:
  schedule:
    - cron: "*/30 * * * *"   # Runs every 30 minutes
  workflow_dispatch:

jobs:
  update-cookie:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y jq curl

    - name: Fetch JSON & Extract Cookie
      run: |
        set -euo pipefail

        # Fetch JSON
        echo "Fetching JSON..."
        curl -s "https://pkll.xojiv79335.workers.dev/" > full.json || { echo "Failed to fetch JSON"; exit 0; }

        # Extract channel_url
        url=$(jq -r '.[] | select(.channel_name=="Star Sports Select 1 HD") | .channel_url' full.json || echo "")

        if [ -z "$url" ]; then
          echo "Channel 'Star Sports Select 1 HD' not found or channel_url empty"
          exit 0
        fi

        # Extract hdnea cookie safely
        cookie=$(echo "$url" | sed -n 's/.*\(hdnea=[^&]*\).*/\1/p')

        if [ -z "$cookie" ]; then
          echo "hdnea cookie not found in channel_url"
          exit 0
        fi

        # Write cookie.json
        echo "{\"cookieHeader\": \"$cookie\"}" > cookie.json
        echo "cookie.json created successfully with cookie: $cookie"

    - name: Commit & Push
      run: |
        if ! git diff --quiet; then
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add cookie.json
          git commit -m "Auto-update Star Sports Select 1 HD cookie"
          git push
