name: Update Cookie JSON

on:
  schedule:
    - cron: "*/30 * * * *" # every 30 minutes
  workflow_dispatch:        # manual trigger

jobs:
  update-cookie:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install requests

      - name: Fetch cookie and update JSON
        run: python fetch_cookie.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add cookie.json
          git diff --quiet || git commit -m "Update cookie.json"
          git push
