name: Update Cookie JSON

on:
  schedule:
    - cron: "*/30 * * * *" # every 30 minutes
  workflow_dispatch:

jobs:
  update-cookie:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install requests

      - name: Fetch cookie and update JSON
        run: python fetch_cookie.py

      - name: Set up Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add, commit and push changes
        run: |
          git add cookie.json
          if ! git diff --cached --quiet; then
            git commit -m "Update cookie.json"
            git push
          else
            echo "No changes to commit"
