name: Auto Update Cookie

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  update-cookie:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install requests
        run: pip install requests

      - name: Run cookie extraction script
        run: python extract_cookie.py

      - name: Commit & Push
        run: |
          if ! git diff --quiet; then
            git config --global user.name "github-actions"
            git config --global user.email "actions@github.com"
            git add cookie.json
            git commit -m "Auto-update Star Sports Select 1 HD cookie"
            git push
          fi
