name: Auto Update Cookie

on:
  schedule:
    - cron: "*/30 * * * *"   # Runs every 30 minutes
  workflow_dispatch:          # Manual trigger

jobs:
  update-cookie:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fetch JSON & Extract Cookie for Star Sports Select 1 HD
        run: |
          # Fetch source JSON
          curl -s "https://pkll.xojiv79335.workers.dev/" > full.json
          
          # Extract channel_url for the specific channel
          url=$(jq -r '.[] | select(.channel_name=="Star Sports Select 1 HD") | .channel_url' full.json)

          # Extract hdnea cookie from URL
          cookie=$(echo "$url" | grep -oP 'hdnea=[^&]+')

          # Write only cookieHeader object
          echo "{\"cookieHeader\": \"$cookie\"}" > cookie.json

      - name: Commit & Push
        run: |
          if ! git diff --quiet; then
            git config --global user.name "github-actions"
            git config --global user.email "actions@github.com"
            git add cookie.json
            git commit -m "Auto-update Star Sports Select 1 HD cookie"
            git push
